// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7Mj03HeJdUQN-bZu32uIn-hS4vdAevM',
    appId: '1:18081031023:web:5def2d6848326030e7fe9a',
    messagingSenderId: '18081031023',
    projectId: 'basiccrudapplication',
    authDomain: 'basiccrudapplication.firebaseapp.com',
    storageBucket: 'basiccrudapplication.appspot.com',
    measurementId: 'G-BJ7H9RJSWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgy9zw5ruHZfJ1Cmc9mOu7ASbizWHKLw8',
    appId: '1:18081031023:android:0be36ee5d2c1a6a8e7fe9a',
    messagingSenderId: '18081031023',
    projectId: 'basiccrudapplication',
    storageBucket: 'basiccrudapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuiTHG9C3d1o27OHOon3MwLTeJI6u6ZA',
    appId: '1:18081031023:ios:3facf09750a9e0a7e7fe9a',
    messagingSenderId: '18081031023',
    projectId: 'basiccrudapplication',
    storageBucket: 'basiccrudapplication.appspot.com',
    iosBundleId: 'com.example.basicCrudApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuiTHG9C3d1o27OHOon3MwLTeJI6u6ZA',
    appId: '1:18081031023:ios:3facf09750a9e0a7e7fe9a',
    messagingSenderId: '18081031023',
    projectId: 'basiccrudapplication',
    storageBucket: 'basiccrudapplication.appspot.com',
    iosBundleId: 'com.example.basicCrudApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr7Mj03HeJdUQN-bZu32uIn-hS4vdAevM',
    appId: '1:18081031023:web:9ae554e7e1e551c4e7fe9a',
    messagingSenderId: '18081031023',
    projectId: 'basiccrudapplication',
    authDomain: 'basiccrudapplication.firebaseapp.com',
    storageBucket: 'basiccrudapplication.appspot.com',
    measurementId: 'G-K0QVX3E9QP',
  );

}